name: xiumusic
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.9.31
  window_manager: ^0.2.8
  dio: ^4.0.6
  crypto: ^3.0.2
  sqflite: ^2.2.2  
  path: ^1.8.2 
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3  

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: fonts/NotoSansSC-Regular.otf
    - family: ChivoMono
      fonts:
        - asset: fonts/ChivoMono-Regular.ttf
